stages:
- publish

publish_pypi:
  stage: publish
  only:
  - tags
  image: python:3.7-alpine
  variables:
    TWINE_USERNAME: $LIVE_PYPI_USERNAME
    TWINE_PASSWORD: $LIVE_PYPI_PASSWORD
  before_script:
  - pip install twine
  - python setup.py sdist
  script:
  - twine upload dist/*
